blank_issues_enabled: true
contact_links:
  - name: Blank issue
    url: https://github.com/dataresponsibly/xai-ranking-benchmark/issues/new
    # about: Please note that Github Discussions should be used in most cases instead
